### ISSUE TITLE
lesson1 hello world from laravel

### ISSUE THREAD

**Issue by nooneqwq** [agangdi/wx-miniprogram-mini-course#11]
![image](https://user-images.githubusercontent.com/53965772/89707337-97524480-d99f-11ea-8fd2-790411cbe742.png)
Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in C:\Users\Administrator\Downloads\code\wx-miniprogram-mini-course-master\lesson1\laravel\bootstrap\app.php:14 Stack trace: #0 C:\Users\Administrator\Downloads\code\wx-miniprogram-mini-course-master\lesson1\laravel\public\index.php(38): require_once() #1 {main} thrown in C:\Users\Administrator\Downloads\code\wx-miniprogram-mini-course-master\lesson1\laravel\bootstrap\app.php on line 14
[https://stackoverflow.com/questions/29764368/fatal-error-class-illuminate-foundation-application-not-found](url) 
还是没有解决。有遇到过这个问题的小伙伴吗？求解谢谢。

**Comment by nooneqwq** [comment]
C:\Users\Administrator\Downloads\code\wx-miniprogram-mini-course-master\lesson1\laravel>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException

  Please provide a valid cache path.

  at C:\Users\Administrator\Downloads\code\wx-miniprogram-mini-course-master\lesson1\laravel\vendor\laravel\framework\src\Illuminate\View\Compilers\Compiler.php:36
    32|      */
    33|     public function __construct(Filesystem $files, $cachePath)
    34|     {
    35|         if (! $cachePath) {
  > 36|             throw new InvalidArgumentException('Please provide a valid cache path.');
    37|         }
    38|
    39|         $this->files = $files;
    40|         $this->cachePath = $cachePath;

  1   C:\Users\Administrator\Downloads\code\wx-miniprogram-mini-course-master\lesson1\laravel\vendor\laravel\framework\src\Illuminate\View\ViewServiceProvider.php:91
      Illuminate\View\Compilers\Compiler::__construct(Object(Illuminate\Filesystem\Filesystem))

  2   C:\Users\Administrator\Downloads\code\wx-miniprogram-mini-course-master\lesson1\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
      Illuminate\View\ViewServiceProvider::Illuminate\View\{closure}(Object(Illuminate\Foundation\Application), [])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

这是composer update的结果

**Comment by agangdi** [comment]
provide a cache path 问题：((进入 storage 并创建几个文件夹，并且给写权限) 
cd storage 
mkdir framework
mkdir framework/cache && framework/cache/data
mkdir framework/sessions
mkdir framework/testing
mkdir framework/views

**Comment by nooneqwq** [comment]
> provide a cache path 问题：((进入 storage 并创建几个文件夹，并且给写权限)
> cd storage
> mkdir framework
> mkdir framework/cache && framework/cache/data
> mkdir framework/sessions
> mkdir framework/testing
> mkdir framework/views
